[package]
name = "rust-yaml-flat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }
regex = "1.8.3"
serde_yaml = "0.9.21"
yaml-rust = "0.4.5"
